{"name": "test_003", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 is '1'", "trace": "E   AssertionError: assert 1 is '1'"}, "description": "第三个测试用例", "start": 1598409647874, "stop": 1598409647874, "uuid": "99d5d451-5b88-45ec-9b9e-33660e9b5e41", "historyId": "50ba7917f2f9dab2e67b45b18c973a80", "testCaseId": "0ed793324da7e527af08def7e9f666c6", "fullName": "test_login_html.TestLogin#test_003", "labels": [{"name": "suite", "value": "test_login_html"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-O3VG549U"}, {"name": "thread", "value": "14388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_html"}]}